import './globals.css'
import { Montserrat } from 'next/font/google'
import Header from "@/app/Component/Header";

const monsterrat = Montserrat({
  weight:'400',
  subsets: ['latin'],
  display:'swap'
})
export const metadata = {
  title: 'Money Making Site',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en" className={monsterrat.className}>
      <body >
        <Header/>

      {children}</body>
    </html>
  )
}
